package com.ChatApplication.ChatApplication.Model;

import jakarta.persistence.*;

/**
 * Entity class representing a user in the chat application.
 * This class is mapped to the "users" table in the database.
 */
@Entity
@Table(name = "users")  // Explicitly set the table name
public class UserModel {

    /**
     * Unique identifier for each user.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /**
     * Unique email of the user. Cannot be null.
     */
    @Column(unique = true, nullable = false)
    private String email;

    /**
     * Name of the user. Cannot be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * Phone number of the user. Cannot be null.
     */
    @Column(nullable = false)
    private String phone;

    /**
     * Indicates whether the user is currently online.
     */
    private boolean isOnline;

    // Getters and Setters

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public boolean isOnline() {
        return isOnline;
    }

    public void setOnline(boolean online) {
        isOnline = online;
    }

    /**
     * Constructor with parameters to initialize a user instance.
     */
    public UserModel(Integer id, String email, String name, String phone, boolean isOnline) {
        this.id = id;
        this.email = email;
        this.name = name;
        this.phone = phone;
        this.isOnline = isOnline;
    }

    /**
     * Default constructor for JPA.
     */
    public UserModel() {
    }

    /**
     * Returns a string representation of the UserModel object.
     */
    @Override
    public String toString() {
        return "UserModel{" +
                "id=" + id +
                ", email='" + email + '\'' +
                ", name='" + name + '\'' +
                ", phone='" + phone + '\'' +
                ", isOnline=" + isOnline +
                '}';
    }
}
